import React from 'react';
import { render } from '@testing-library/react-native';
import { AIDisclaimer } from './AIDisclaimer';

describe('AIDisclaimer', () => {
  it('renders without crashing', () => {
    const { getByTestId } = render(<AIDisclaimer />);
    expect(getByTestId('ai-disclaimer')).toBeTruthy();
  });

  it('shows the AI-Generated Recipe heading', () => {
    const { getByText } = render(<AIDisclaimer />);
    expect(getByText('AI-Generated Recipe')).toBeTruthy();
  });

  it('shows the informational disclaimer text', () => {
    const { getByText } = render(<AIDisclaimer />);
    expect(
      getByText(/Recipes are generated by AI and are for informational purposes only/i)
    ).toBeTruthy();
  });

  it('mentions allergen verification', () => {
    const { getByText } = render(<AIDisclaimer />);
    expect(getByText(/Always verify allergen information with product labels/i)).toBeTruthy();
  });

  it('mentions consulting a healthcare provider', () => {
    const { getByText } = render(<AIDisclaimer />);
    expect(getByText(/Consult a healthcare provider for dietary advice/i)).toBeTruthy();
  });
});
